[package]
name = "walless-wasm"
version = "0.1.0"
authors = ["Metacraft <atem@stormgate.io>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
ring = "0.17.0-alpha.11"
base64 = "0.21.0"

[dependencies.wasm-bindgen]
version = "0.2.84"
features = ["serde-serialize"]
